apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sports-exchange

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - matching-engine.yaml
  - agent-portal.yaml
  - player-portal.yaml
  - ingress.yaml
